### ISSUE TITLE
Fix code scanning alert - Clear text transmission of sensitive cookie

### ISSUE THREAD

**Issue by carlosferreyra** [Seminario-Integrador-2024/GestionTUP#49]
__Tracking issue for:__
- [ ] https://github.com/Seminario-Integrador-2024/GestionTUP/security/code-scanning/2

@Seminario-Integrador-2024/frontend 

# Hola Chicos, les abro una Issue para que revisen el codigo:

*el escaner detecta que estan transmitiendo informacion sensible por texto plano en las cookies. en el link de arriba, el dependabot les da una posible solucion, @TobiasMaciel te menciono porque la alerta vino de un commit tuyo.*

**Comment by samuop** [comment]
Igual todo se está transfiendo en texto plano, no solo las cookies porque la  conexión con el back es HTTP 👀

**Comment by carlosferreyra** [comment]
ok, eso no sabia... pense que la conexion a la api la hacia a traves de https.... denme unas horas, y configuro el #GoogleCloudRun para que funcione con https... es pago https, pero creo que google ofrece gratis.
https://cloud.google.com/load-balancing/docs/ssl-certificates/google-managed-certs?hl=en

**Comment by TobiasMaciel** [comment]
En el ultimo
